name: example_workcell
include: ['wei.compose.yaml']
services:
  ###########
  # Modules #
  ###########
  # sleep_node:
  #   image: ghcr.io/ad-sdl/sleep_module
  #   container_name: sleep_node
  #   ports:
  #     - 2000:2000
  #   env_file:
  #     - .env
  # webcam_node:
  #   image: ghcr.io/ad-sdl/webcam_module
  #   container_name: webcam_node
  #   privileged: true # needed for hardware access
  #   devices:
  #     - /dev/video0:/dev/video0
  #   ports:
  #     - 2001:2001
  #   command: python webcam_module/src/webcam_rest_node.py --port 2001
  #   env_file:
  #     - .env
  ur_module:
    container_name: ur_module
    image: ghcr.io/ad-sdl/ur_module
    command: python -m ur_rest_node --port 3011 --ur_ip ${UR_IP}
    env_file: .env
    ports:
      - 3011:3011